### ISSUE TITLE
Malformed zip file when installing some CurseForge packs

### ISSUE THREAD

**Issue by RyanTheAllmighty** [ATLauncher/ATLauncher#474]
Not sure why this happens. Happens on specific packs, namely:

- Better Minecraft [FORGE]

I've attempted to figure out why, but seems for whatever reason, the zip processing within Java itself sees these zip files as malformed.

Since every third party library uses the internal Java zip classes to do decompression, we might need to defer to downloading 7z and then using that to extract these. I really don't want to do that, but I don't know if there is any other choice.

```
[07/06/2021 10:19:26 AM] java.lang.IllegalArgumentException: MALFORMED
	at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
	at java.util.zip.ZipFile.getZipEntry(ZipFile.java:583)
	at java.util.zip.ZipFile.access$900(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:539)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:514)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:495)
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:504)
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:472)
	at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:996)
	at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:939)
	at com.atlauncher.workers.InstanceInstaller.generatePackVersionFromCurseForge(InstanceInstaller.java:443)
	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:220)
	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:118)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by RyanTheAllmighty** [comment]
So looks like the actual issue is a file in the archive having certain characters in it.

For the example of Better Minecraft [FORGE] it looks like it's the file `§cAdvanced GUI §8DARK §c1.16 §f[OF] §r.zip`:

`java.nio.file.InvalidPathException: Illegal char <?> at index 24: overrides/resourcepacks/?cAdvanced GUI ?8DARK ?c1.16 ?f[OF] ?r.zip`

**Comment by RyanTheAllmighty** [comment]
Apache Commons Compress seems to be able to work with these files, so going to set it up so it tries using the built in Java methods to interact with zip files, then if that fails, fall back to Apache Commons Compress. Seems like the only way forward.

**Comment by RyanTheAllmighty** [comment]
Only issue is that these files that it fails on, won't get extracted with their correct name since when we try to grab the name of the entry, it replaces then with `?` which needs to get removed in order to write the file to disk. Going to have to deal with that as there doesn't seem to be any other solution that I can find.

**Comment by RyanTheAllmighty** [comment]
This has been fixed with version 3.4.4.3

**Comment by Daupaloffer** [comment]
This issue still occurs for me on 3.4.4.3. I've tested it with Better Minecraft [FORGE] versions 19, 19.5, 20, 21, and 22, all give me the same error.

```
[2021-06-12 04:01:27 AM] java.lang.IllegalArgumentException: MALFORMED
	at java.util.zip.ZipCoder.toString(Unknown Source)
	at java.util.zip.ZipFile.getZipEntry(Unknown Source)
	at java.util.zip.ZipFile.access$900(Unknown Source)
	at java.util.zip.ZipFile$ZipEntryIterator.next(Unknown Source)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(Unknown Source)
	at java.util.zip.ZipFile$ZipEntryIterator.nextElement(Unknown Source)
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:504)
	at org.zeroturnaround.zip.ZipUtil.iterate(ZipUtil.java:472)
	at org.zeroturnaround.zip.ZipUtil.unpack(ZipUtil.java:996)
	at com.atlauncher.utils.ArchiveUtils.extract(ArchiveUtils.java:109)
	at com.atlauncher.utils.ArchiveUtils.extract(ArchiveUtils.java:104)
	at com.atlauncher.workers.InstanceInstaller.generatePackVersionFromCurseForge(InstanceInstaller.java:443)
	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:220)
	at com.atlauncher.workers.InstanceInstaller.doInBackground(InstanceInstaller.java:118)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

Here's my full ATLauncher log: https://paste.atlauncher.com/view/5590fb9f-e102-4c90-aa01-b266ea89099e

**Comment by RyanTheAllmighty** [comment]
Okay should hopefully be fixed next update. I'll push out a little later today

**Comment by RyanTheAllmighty** [comment]
This has been fixed with version 3.4.4.4
